export const SLIDER_SEC = 3000;
export const ARTICLE_PER_PAGE = 5;
export const GAMES_PER_PAGE = 12;
export const GENRES = [
  "MMORPG",
  "SHOOTER",
  "STRATEGY",
  "MOBA",
  "RACING",
  "SPORTS",
  "SOCIAL",
  "SANDBOX",
  "OPEN-WORLD",
  "SURVIVAL",
  "PVP",
  "PVE",
  "PIXEL",
  "VOXEL",
  "ZOMBIE",
  "TURN-BASED",
  "FIRST-PERSON",
  "THIRD-PERSON",
  "TOP-DOWN",
  "TANK",
  "SPACE",
  "SAILING",
  "SIDE-SCROLLER",
  "SUPERHERO",
  "PERMADEATH",
  "CARD",
  "BATTLE-ROYALE",
  "MMO",
  "MMOFPS",
  "MMOTPS",
  "3D",
  "2D",
  "ANIME",
  "FANTASY",
  "SCI-FI",
  "FIGHTING",
  "ACTION-RPG",
  "ACTION",
  "MILITARY",
  "MARTIAL-ARTS",
  "FLIGHT",
  "LOW-SPEC",
  "TOWER-DEFENSE",
  "HORROR",
  "MMORTS",
];

export const API_MB = "https://mmo-games.p.rapidapi.com/";
export const OPTIONS = {
  method: "GET",
  headers: {
    "x-rapidapi-key": "9eb5e798ffmsh4bf21a7ceea3858p19b264jsnef611d0eb409",
    "x-rapidapi-host": "mmo-games.p.rapidapi.com",
  },
};
